### ISSUE TITLE
Unable to add package because Xcode's git does not support git-lfs

### ISSUE THREAD

**Issue by clindsay3** [shinjukunian/zinnia-swift#1]
When I try to add this package via Xcode, I get this mysterious error:
<img width="659" alt="Screen Shot 2022-02-18 at 3 14 38 PM" src="https://user-images.githubusercontent.com/227043/154755062-b22cda2f-2932-4f84-b36f-3660d5406dff.png">

After some digging, I found this error message:
<img width="475" alt="Screen Shot 2022-02-18 at 3 14 59 PM" src="https://user-images.githubusercontent.com/227043/154755123-e6928e35-4f30-4dd2-94f9-698531b30652.png">

And sure enough, it looks like SwiftPM [doesn't support git-lfs currently](https://forums.swift.org/t/swiftpm-with-git-lfs/42396), at least without symlinking it in from another git installation, and remembering to update it every time you update Xcode.

I'd rather avoid going down that path if possible. It looks like the only git-lfs file is a model used in the tests. Maybe it would be OK in this case to simply include it in the repo, without using git-lfs? Or maybe require that it would be downloaded separately in order to run tests?

@shinjukunian If you have a preferred way, I'd be happy to put together a pull request. Thanks for making this package, it looks great!

**Comment by clindsay3** [comment]
I just realized this has been fixed on master! I'll just go ahead and use that branch. Sorry to bother you. 🙂

**Comment by shinjukunian** [comment]
Hi Chris,
I ran into the same problem and decided to ditch git-lfs. Glad things have worked out for you.

Please let me know if there is anything else you'd like to see added or fixed.

Cheers from Tokyo

Morten

**Comment by clindsay3** [comment]
Thanks, I'll let you know! 👍
